-- Even Fibonacci Numbers:
-- Each new term in the Fibonacci sequence is generated by
-- adding the previous two terms. By starting with 1 and 2,
-- the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
-- By considering the terms in the Fibonacci sequence whose values
-- do not exceed four million, find the sum of the even-valued terms.

fib :: Integer -> Integer
fib 1 = 1
fib 2 = 2
fib n = fib (n - 1) + fib (n - 2)

fibs :: Integer -> [Integer]
fibs start = fib start : fibs (start + 1)

result :: Integer
result = foldl (+) 0 (filter even (takeWhile (< 4000000) (fibs 1)))

-- :load 0002.hs
-- takeWhile (< 4000000) (fibs 1)
-- filter even (takeWhile (< 4000000) (fibs 1))
-- foldl (+) 0 (filter even (takeWhile (< 4000000) (fibs 1)))
-- 4613732
