-- Highly Divisible Triangular Number:
-- The sequence of triangle numbers is generated by adding the
-- natural numbers. So the 7th triangle number would be
-- 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
-- 1, 3, 6, 10, 15, 21, 28, 36, 45, 55...
-- Let us list the factors of the first seven triangle numbers:
-- 1: 1
-- 3: 1, 3
-- 6: 1, 2, 3, 6
-- 10: 1, 2, 5, 10
-- 15: 1, 3, 5, 15
-- 21: 1, 3, 7, 21
-- 28: 1, 2, 4, 7, 14, 28
-- We can see that 28 is the first triangle number to have over
-- five divisors.
-- What is the value of the first triangle number to have over
-- five hundred divisors?

import Utils

triangular :: Integer -> Integer
triangular num = sum (rangeUp 1 1 num)

triangular2 :: Integer -> Integer
triangular2 num = (div (num * (num + 1)) 2)

triangulars :: [Integer]
triangulars = triangularsAux 1 where
    triangularsAux start = triangular2 start : triangularsAux (start + 1)

findTriangular :: Integer -> Int -> Integer
findTriangular num target =
    let tri = triangular2 num
        lenDiv = length (divisors tri) in
            if lenDiv > target then tri else findTriangular (num + 1) target

result :: Integer
result = findTriangular 1 5

-- :load 0012.hs
-- triangular 7
-- take 10 triangulars
-- divisors 28
-- 
