-- Distinct Powers:
-- Consider all integer combinations of a^b for
-- 2 <= a <= 3 and 2 <= a <= 3:
-- 2^2 = 4
-- 2^3 = 8
-- 3^2 = 9
-- 3^3 = 27
-- If they are then placed in numerical order, with any repeats removed,
-- we get the following sequence of 4 distinct terms:
-- 4, 8, 9, 27
-- How many distinct terms are in the sequence generated by a^b for
-- 2 <= a <= 100 and 2 <= a <= 100?

import Utils (getCombs, removeDups)

result :: Int
result = length $ removeDups $ map (\(x, y) -> x ^ y) $ getCombs 2 100

-- :load 0029.hs
-- getCombs 5
-- length $ removeDups $ map (\(x, y) -> x ^ y) $ getCombs 2 100
-- 9183
