% Even Fibonacci Numbers:
% Each new term in the Fibonacci sequence is generated by
% adding the previous two terms. By starting with 1 and 2,
% the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
% By considering the terms in the Fibonacci sequence whose values
% do not exceed four million, find the sum of the even-valued terms.

:- include('util.pl').

fibonacci(1, 1) :- !.
fibonacci(2, 2) :- !.
fibonacci(N, Fib) :-
    N1 #= N - 1,
    N2 #= N - 2,
    fibonacci(N1, A),
    fibonacci(N2, B),
    Fib #= A + B.

fibonacci_list(Length, List) :-
    do_list(Length, Nums),
    maplist(fibonacci, Nums, List).

golden(Golden) :-
    Golden = 1/2 * (1 + sqrt(5)).

fibonacci2(N, Result) :-
    golden(Golden),
    Fib = round((Golden ** N) / sqrt(5)),
    evaluate(Fib, Result).

start(FibSum) :-
    do_list(fibonacci2, 33, FibList),
    include(is_even, FibList, FibList2),
    sum_list(FibList2, FibSum).

% gprolog
% ['0002'].
% do_list(fibonacci2, 33, List).
% start(FibSum).
% 4613732
