% Pentagon Numbers:
% Pentagonal numbers are generated by the formula,
% P_n = n * (3 * n - 1) / 2.
% The first ten pentagonal numbers are:
% 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
% It can be seen that P_4 + P_7 = 22+ 70 = 92 = P_8. However,
% their difference, 70 - 22 = 48, is not pentagonal.
% Find the pair of pentagonal numbers, P_j and P_k, for which
% their sum and difference are pentagonal and D = |P_k - P_j| is
% minimised; what is the value of D?

pentagonal(P, N) :-
    fd_max_integer(Max),
    fd_domain([P, N], 1, Max),
    N #= P * (3 * P - 1) / 2,
    fd_labeling([P, N]).

start(J, JN, K, KN, D) :-
    fd_domain([J, JN, K, KN, A, B, C, D], 1, 10000000),
    pentagonal(J, JN),
    pentagonal(K, KN),
    C #= KN + JN,
    D #= KN - JN,
    pentagonal(A, C),
    pentagonal(B, D),
    fd_labeling([J, JN, K, KN, A, B, C, D]).

% gprolog
% ['0044'].
% pentagonal(P, N).
% start(J, JN, K, KN, D).
% D = 5482660
% J = 1020
% JN = 1560090
% K = 2167
% KN = 7042750
