# Triangular, Pentagonal, and Hexagonal:
# Triangle, pentagonal, and hexagonal numbers are generated by the
# following formulae:
# Triangle:   T_n = n * (n + 1) / 2
# Pentagonal: P_n = n * (3 * n - 1) / 2
# Hexagonal:  H_n = n * (2 * n - 1)
# It can be verified that T_285 = P_165 = H_143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.

import math


def is_int(num: float) -> bool:
    fractional, _ = math.modf(num)
    return fractional == 0


def inv_triangular(num: float) -> float:
    n = (math.sqrt(8 * num + 1) - 1) / 2
    return n if is_int(n) else 0


def inv_pentagonal(num: float) -> float:
    n = (math.sqrt(24 * num + 1) + 1) / 6
    return n if is_int(n) else 0


def inv_hexagonal(num: float) -> float:
    n = (math.sqrt(8 * num + 1) + 1) / 4
    return n if is_int(n) else 0

def hexagonal(num: int) -> int:
    return num * (2 * num - 1)


def find_tri_pen_hex(start=2):
    counter = start

    while True:
        h = hexagonal(counter)
        inv_p = inv_pentagonal(h)

        if inv_p != 0:
            inv_t = inv_triangular(h)

            if inv_t != 0:
                return (counter, int(inv_p), int(inv_t), h)

        counter += 1


if __name__ == "__main__":
    # print(find_tri_pen_hex())
    # (143, 165, 285, 40755)
    print(find_tri_pen_hex(144))
    # (27693, 31977, 55385, 1533776805)
